#日志配置
logging:
  file:
    name: logger/websys.log
  level:
    root: error
    cn.hlsd.websys: info
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/websys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

mybatis:
  type-aliases-package: cn.hlsd.websys.entity
  mapper-locations: classpath:/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml